### ISSUE TITLE
Unable to extract exons from gff file

### ISSUE THREAD

**Issue by oalavijeh** [wrf/pdbcolor#2]
Firstly, thank you for this awesome tool! I am not really used to using python but was hoping you could help me. I am trying to annotate the exons and introns onto the protein structure for the gene IFT140

- I have downloaded the gff3 file for the gene of interest IFT140: https://www.ncbi.nlm.nih.gov/nuccore/NM_014714.4?report=genbank&to=5232 by clicking "send to" -> "file" -> "complete Record"  -> GFF3 
- I then did: `grep NM_014714.4 IFT140.gff3 > ift140.gff` to get the relevant gff file 
- I then ran: python gff_cds_to_pymol_script.py -g IFT140.gff3 > color_ppyr_ift140.pml 
- This gave me: 

Parsing GFF file IFT140.gff3 for None  
Finished parsing IFT140.gff3, read 37 lines  
WARNING COULD NOT FIND ANY EXONS FOR None
Found 0 exons, 0 bases for 0 residues
0 codons are out of phase

- I have tried: python gff_cds_to_pymol_script.py -g IFT140.gff3 -i AF-Q96RY7-F1-model_v1.pdb > color_ppyr_ift140.pml
(where AF-Q96RY7-F1-model_v1.pdb  is the pdb file for IFT140 taken from the alphafold website) but this give me the same error as above

- I have also tried: 
- python gff_cds_to_pymol_script.py -g ift140.gff -i NM_014714.4 > color_ppyr_ift140.pml but this give me the same error as above

Your help would be much appreciated. 

All the best

**Comment by wrf** [comment]
Hello,
It says there are 0 exons found, since it should be expecting exon features.
Can you please post first few lines (of the 37 found) from the file IFT140.gff3 ?
Thanks

**Comment by oalavijeh** [comment]
##sequence-region NM_014714.4 1 5232
NM_014714.4	RefSeq	region	1	5232	.	+	.	ID=NM_014714.4:1..5232;Dbxref=taxon:9606;Name=16;chromosome=16;gbkey=Src;genome=genomic;map=16p13.3;mol_type=mRNA
NM_014714.4	RefSeq	gene	1	5232	.	+	.	ID=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;Name=IFT140;description=intraflagellar transport 140;gbkey=Gene;gene=IFT140;gene_synonym=c305C8.4,c380F5.1,gs114,MZSDS,RP80,SRTD9,WDTC2
NM_014714.4	RefSeq	CDS	327	4715	.	+	0	ID=cds-NP_055529.2;Parent=gene-IFT140;Dbxref=CCDS:CCDS10439.1,Genbank:NP_055529.2,GeneID:9742,HGNC:HGNC:29077,MIM:614620;Name=NP_055529.2;gbkey=CDS;gene=IFT140;product=intraflagellar transport protein 140 homolog;protein_id=NP_055529.2
NM_014714.4	RefSeq	exon	1	105	.	+	.	ID=id-IFT140;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	106	295	.	+	.	ID=id-IFT140-2;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	296	473	.	+	.	ID=id-IFT140-3;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	474	695	.	+	.	ID=id-IFT140-4;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	696	817	.	+	.	ID=id-IFT140-5;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	818	960	.	+	.	ID=id-IFT140-6;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	961	1136	.	+	.	ID=id-IFT140-7;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1137	1228	.	+	.	ID=id-IFT140-8;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1229	1335	.	+	.	ID=id-IFT140-9;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1336	1481	.	+	.	ID=id-IFT140-10;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1482	1685	.	+	.	ID=id-IFT140-11;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1686	1758	.	+	.	ID=id-IFT140-12;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1759	1850	.	+	.	ID=id-IFT140-13;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1851	1978	.	+	.	ID=id-IFT140-14;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	1979	2096	.	+	.	ID=id-IFT140-15;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	2097	2227	.	+	.	ID=id-IFT140-16;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	2228	2393	.	+	.	ID=id-IFT140-17;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	2394	2525	.	+	.	ID=id-IFT140-18;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	2526	2725	.	+	.	ID=id-IFT140-19;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	2726	2903	.	+	.	ID=id-IFT140-20;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	2904	3094	.	+	.	ID=id-IFT140-21;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	3095	3190	.	+	.	ID=id-IFT140-22;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	3191	3323	.	+	.	ID=id-IFT140-23;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	3324	3467	.	+	.	ID=id-IFT140-24;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	3468	3596	.	+	.	ID=id-IFT140-25;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	3597	3779	.	+	.	ID=id-IFT140-26;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	3780	3986	.	+	.	ID=id-IFT140-27;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	3987	4199	.	+	.	ID=id-IFT140-28;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	4200	4366	.	+	.	ID=id-IFT140-29;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	4367	4508	.	+	.	ID=id-IFT140-30;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	exon	4509	5232	.	+	.	ID=id-IFT140-31;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;gbkey=exon;gene=IFT140;inference=alignment:Splign:2.1.0
NM_014714.4	RefSeq	sequence_feature	306	308	.	+	.	ID=id-IFT140-32;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;Note=upstream in-frame stop codon;gbkey=misc_feature;gene=IFT140
NM_014714.4	RefSeq	polyA_site	5232	5232	.	+	.	ID=id-IFT140-33;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;Note=major polyA site;gbkey=polyA_site;gene=IFT140
NM_014714.4	RefSeq	polyA_signal_sequence	5209	5214	.	+	.	ID=id-IFT140-34;Parent=gene-IFT140;Dbxref=GeneID:9742,HGNC:HGNC:29077,MIM:614620;Note=hexamer: AATAAA;gbkey=regulatory;gene=IFT140;regulatory_class=polyA_signal_sequence

**Comment by oalavijeh** [comment]
![Screenshot from 2021-10-25 15-33-54](https://user-images.githubusercontent.com/56344383/138715598-dd2d039e-8336-4ad2-af5b-9c98e10acf4f.png)

Here is a screenshot if easier

**Comment by wrf** [comment]
You format seems to indicate the entire region is a transcript, rather than the genomic coordinates. There should normally be a separate CDS feature for each exon, so your gene should have 2 dozen or so. Bear in mind that the max colors of the exon coloring was 20 by default, and then they get recycled.

If this is a human gene, you might try downloading the human genome annotation here:

https://www.ncbi.nlm.nih.gov/genome/51?genome_assembly_id=582967

and then following the strategy you outlined above,

something like `gzip -dc GCF_000001405.39_GRCh38.p13_genomic.gff.gz | grep IFT140 > ift140.gff`

and continuing from there.
